### ISSUE TITLE
Initial data migration

### ISSUE THREAD

**Issue by xtoddx** [opendataphilly/Open-Data-Catalog#11]
There is a bit of data required to seed the database in a meaningful way.  Now that South is installed, it would be great for a migration to add those bits of data.  The things I've come across are:
- flatpages [/about/, /faq/, ...]
- update frequencies [daily, weekly, monthly, quarterly, ...]
- url types [API, application, data, documentation, image]
- Data types / formats [CSV, CSV with header, JSON, Shapefile, XML]

There may be others.

**Comment by rcheetham** [comment]
We are archiving this repo as no one is actively using it.
