### ISSUE TITLE
source files for icons?

### ISSUE THREAD

**Issue by max-mapper** [opendataphilly/Open-Data-Catalog#2]
Hey Azavea -- thanks a ton for this project!  It is very nicely designed. I'm wondering if you have the PSDs or equivalent source files for the various nicely designed buttons and icons in the project as they would help when rebranding for other cities.

Cheers,

Max

**Comment by alsaihn** [comment]
Brian has added PSDs of both the generic icons in this project, and the much nicer ones from OpenDataPhilly to the images area.
