### ISSUE TITLE
OpenDataPhilly site name still used on various pages

### ISSUE THREAD

**Issue by mjumbewu** [opendataphilly/Open-Data-Catalog#3]
There are a few places that still use OpenDataPhilly as the site name.

```
/ # (the Twitter account)
/accounts/register/
/ideas/
/opendata/nominate/
...
```

Maybe use the Sites framework and pass some `site_name` variable to the templates to help white-label the platform.

**Comment by alsaihn** [comment]
Resolved by commit: https://github.com/azavea/Open-Data-Catalog/commit/aa39d18f28196aad544da2aed5a2832094bb6ba0
