### ISSUE TITLE
Integration with Data.gov

### ISSUE THREAD

**Issue by mheadd** [opendataphilly/Open-Data-Catalog#31]
It appears that the stewards of Data.gov have set up ways for city data portals to integrate and have their data sets listed in the [Cities community](http://cities.data.gov).

http://project-open-data.github.io/catalog/

In essence, integration involves generating a [compliant](http://project-open-data.github.io/schema/) data.json that lives at the root URL of participating sites. It would be awesome if there was a way to generate a data.json file for ODC sites.

**Comment by tomkralidis** [comment]
@mheadd FYI ODC is built with pycsw for CSW search/discovery/federation.  It might be easier to put this functionality in pycsw, which ODC then leverages as a result.  This would then make both ODC and non-ODC pycsw deployments data.gov friendly, encouraging even more integration.

Thoughts?

cc @jj0hns0n FYI

**Comment by andrewbt** [comment]
What a coincidence! I just met and spoke to @JeanneHolm from Data.gov this evening about these very plans of theirs.

**Comment by mheadd** [comment]
@andrewbt - I've spoken with @JeanneHolm about this in the past in general terms. Not sure there was ever a specific document before now that listed exactly how to do this.

@tomkralidis I'm not a Python dude, so I'll defer to you (and others) on your suggested approach. I just think this would make the ODC platform much more powerful, allowing users to integrate with the largest data repository on the country. Let's do this!

**Comment by JeanneHolm** [comment]
There are a few options and open to what works best. Cities connect to http://Cities.Data.gov via federation, JSON, technologies like CKAN, Socrata or Junar, or even CSV files. How can we make it work with ODC too? Agreed on "let's do this!".

**Comment by waldoj** [comment]
The U.S. Department of Health and Human Services [has created a data.json plugin for CKAN](https://github.com/HHS/ckanext-datajson), which they provide on their GitHub repository. I mention that because portions of that program might be useful to provide similar functionality within ODC.

**Comment by mheadd** [comment]
Agreed. It would be great to see a similar plug in for ODC. Something that generates a compliant data.json file.

@JeanneHolm - if such a plugin is built, and used by ODC site operators, what is the process for getting integrated with Data.gov? I assume the URL to the new data.json file needs to be added somewhere. Is there a process or point of contact for this?

**Comment by JeanneHolm** [comment]
We are working on expanding the options for cities to make their data accessible through Cities.Data.gov with the migration to our new interface (see http://Next.Data.gov). We could embed the option for ODC (and the others) prominently on the new site, but we could work on the plug-in now and integrate OpenPhilly today.

**Comment by tomkralidis** [comment]
FYI a first pass is now implemented in master (2c9e5337dcebf144466028dce25618df52cf36d2).

**Comment by waldoj** [comment]
:1

**Comment by waldoj** [comment]
Huh, apparently GitHub's mobile site doesn't parse emoji. :-/ Anyhow, yay!

**Comment by andrewbt** [comment]
That's cool! Thanks Tom!

On Mon, Jan 13, 2014 at 9:25 AM, Waldo Jaquith notifications@github.comwrote:

> Huh, apparently GitHub's mobile site doesn't parse emoji. :-/ Anyhow, yay!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/azavea/Open-Data-Catalog/issues/31#issuecomment-32173003
> .

## 

Andrew Thompson, Community Evangelist

Azavea |  340 N 12th St, Ste 402, Philadelphia, PA
athompson@azavea.com  | T 215.701.7689  | F 215.925.2663
Web azavea.com http://www.azavea.com/  |  Blog
azavea.com/blogshttp://www.azavea.com/Blogs
| Twitter @azavea http://twitter.com/azavea

Join our community! Google Groups:
Cicero API http://www.azavea.com/products/cicero/community/user-community/|
OpenTreeMaphttps://groups.google.com/forum/?fromgroups#!forum/opentreemap-user|
GeoTrellishttps://groups.google.com/forum/?fromgroups#!forum/geotrellis-user|
OpenDataCataloghttps://groups.google.com/forum/?fromgroups#!forum/opendatacatalog-user

**Comment by rcheetham** [comment]
We are archiving this repo as no active work is being done or expected.
