### ISSUE TITLE
Typo in Philly api-doc

### ISSUE THREAD

**Issue by tlevine** [opendataphilly/Open-Data-Catalog#38]
I don't think this typo has made its way to the Open-Data-Catalog codebase,
but I'm posting this here just in case. I've also emailed info@opendataphilly.org.

http://opendataphilly.org/api-doc/ provides conflicting routes
for the API search endpoint; the two endpoints are

```
http://www.opendataphilly.org/api/resources/search?qs={keyword}
http://www.opendataphilly.org/api/resource/search/?qs={keyword}
```

The first of these is correct, and the second is not;
"resources" must be plural, and there may be no trailing slash.

**Comment by rcheetham** [comment]
We are archiving this repo as no active work is being done or expected.
