### ISSUE TITLE
PIL not supported anymore

### ISSUE THREAD

**Issue by snmateen** [opendataphilly/Open-Data-Catalog#40]
requirements.txt has PIL (unsupported) package. 

[localhost] out: Collecting PIL==1.1.7 (from -r requirements.txt (line 2))
[localhost] out:   Could not find a version that satisfies the requirement PIL==1.1.7 (from -r requirements.txt (line 2)) (from versions: )
[localhost] out: No matching distribution found for PIL==1.1.7 (from -r requirements.txt (line 2))

**Comment by glw** [comment]
this worked for me
pip install --no-index -f http://dist.plone.org/thirdparty/ -U PIL
