### ISSUE TITLE
Response from /data.json endpoint is not in standard format.

### ISSUE THREAD

**Issue by kennyshittu** [opendataphilly/Open-Data-Catalog#41]
Base on the code changes made here https://github.com/azavea/Open-Data-Catalog/commit/1ab582544b8e987d192ad1a2068622894d9f152b

I see the endpoint just returns an array of datasets as oppose following the structure specified here  https://project-open-data.cio.gov/v1.1/schema/ . That breaks implementation on our side cos we're getting a json array instead of the expected json object.  Can we make changes to follow the standard structure : 
```
{
  "@context": "https://project-open-data.cio.gov/v1.1/schema/catalog.jsonld",
  "@id": "https://data.chattlibrary.org/data.json",
  "@type": "dcat:Catalog",
  "conformsTo": "https://project-open-data.cio.gov/v1.1/schema",
  "describedBy": "https://project-open-data.cio.gov/v1.1/schema/catalog.json",
  "dataset": []
}
```
Or if changing will break impl for existing clients, We can add a new endpoint that follows the above format.

**Comment by rcheetham** [comment]
We are archiving this repo as no active work is being done or expected.
